### ISSUE TITLE
Support standard multiarch binary names

### ISSUE THREAD

**Issue by giminni** [webdevops/go-crond#20]
I am using go-crond in a multi arch environment and fight with the non common binary architecture names like:
- go-crond-64-linux
- go-crond-64-osx

Please change it to something like:
- go-crond-linux-amd64
- go-crond-linux-darwin

See https://github.com/docker-library/official-images#multiple-architectures

**Comment by steinhobelgruen** [comment]
While I agree that „64“ does not fully describe the architecture, just going with docker‘s list will also not cut it.
Docker for example does not support macOS directly and thus has no architecture name for it.
„go-crond-linux-darwin“ would just be plain wrong.

**Comment by giminni** [comment]
Agreed, my fault
should be "go-crond-darwin-amd64"

**Comment by mblaschke** [comment]
would this be more suitable?

```
go-crond-darwin-amd64
go-crond-darwin-arm64
go-crond-linux-amd64
go-crond-linux-amd64-dynamic
go-crond-linux-arm32v6
go-crond-linux-arm32v6-dynamic
go-crond-linux-arm64v8
go-crond-linux-arm64v8-dynamic
go-crond-linux-i386
go-crond-linux-i386-dynamic
```

**Comment by steinhobelgruen** [comment]
Those make sense.

**Comment by mblaschke** [comment]
New artificats are now released via github actions but changed layout:

```
go-crond.${GOOS}.${GOARCH}
```
