### ISSUE TITLE
Docker image runs as root

### ISSUE THREAD

**Issue by 030** [webdevops/go-crond#25]
The docker image seems to run as root by default.

**Comment by mblaschke** [comment]
You can easily switch the user of a container on runtime (eg `docker run -u 1000:1000` or eg. in Kubernetes).

Also when you're inheriting this container you can change it eg:

DOCKERFILE
```
FROM ...
USER 1000:1000
```

IMHO the main container should be default to root as i don't know on which user it should run in the end. Docker/Container runtimes provides an easy way to switch it.
