### ISSUE TITLE
[Support] Unable to run cron jobs on nth weekday of the month

### ISSUE THREAD

**Issue by Draxter** [webdevops/go-crond#42]
Hi, for some reason my cron job that is meant to run on every second Tuesday of the month, does not honour the day of month range that I give it in a `0 0 8-14 * 2` expression, which I double checked [here](https://crontab.guru/#0_0_8-14_*_2)

**My setup:**
Docker image used: `webdevops/go-crond:23.2.0-alpine`
CMD arguments: `["--auto", "--verbose"]`
My crontabs folder is copied like so: `COPY --chmod=755 crontabs /etc/crontabs`
There I have a cron job `/etc/crontabs/job_1` contains: `0 0 8-14 * 2 /files/job_1.sh`

**The Results**
`docker logs go-crond 2>&1 | grep -i job_1`
```
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","level":"info","msg":"cronjob added","shell":"sh","spec":"0 0 8-14 * 2","time":"2023-06-21T09:04:22+12:00","user":"root"}
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","level":"debug","msg":"executing","shell":"sh","spec":"0 0 8-14 * 2","time":"2023-06-27T00:00:00+12:00","user":"root"}
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","elapsed_s":9306.533054711,"exitCode":0,"level":"info","msg":"finished","result":"success","shell":"sh","spec":"0 0 8-14 * 2","time":"2023-06-27T02:35:06+12:00","user":"root"}
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","level":"debug","msg":"executing","shell":"sh","spec":"0 0 8-14 * 2","time":"2023-07-04T00:00:06+12:00","user":"root"}
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","elapsed_s":9303.841112584,"exitCode":0,"level":"info","msg":"finished","result":"success","shell":"sh","spec":"0 0 8-14 * 2","time":"2023-07-04T02:35:10+12:00","user":"root"}
```

Looks like the 8-14 day of month range is ignored, and the job runs every Tuesday. I also double chcked the date and time on the container, and it's correct. Any ideas?

**Comment by Draxter** [comment]
I have also tried an alternative cron expression `0 0 ? * TUE#2`

However gocrond returns a syntax error:
```
{"command":"/files/job_1.sh","crontab":"/etc/crontabs/job_1","level":"error","msg":"cronjob failed adding: failed to parse int from TUE#2: strconv.Atoi: parsing \"TUE#2\": invalid syntax","shell":"sh","spec":"0 0 ? * TUE#2","time":"2023-07-05T09:02:04+12:00","user":"root"}

```

**Comment by smlx** [comment]
> Looks like the 8-14 day of month range is ignored, and the job runs every Tuesday. I also double chcked the date and time on the container, and it's correct. Any ideas?

From [crontab(5)](https://manpages.debian.org/testing/cron/crontab.5.en.html):

> Commands are executed by cron(8) when the minute, hour, and month of year fields match the current time, **and** when at least one of the two day fields (day of month, or day of week) match the current time.

So that means commands are executed if _either_ of the third (day of month) or fifth (day of week) fields match.

In your case, the command will run at midnight every day between the 8th and 14th (inclusive) of every month, _and_ on every Tuesday.

**Comment by Draxter** [comment]
@smlx Sounds like you are right, and that first cron expression is incorrect. 

For now I worked around it by using a ‘test’ command before running job_1. It checks whether its Tuesday and cron expression runs the job between 8th and 14th. 

Expressions like ‘TUE#2’ still aren’t supported though, which are a part of a cron spec. Might be a useful feature to add.

**Comment by smlx** [comment]
> Expressions like ‘TUE#2’ still aren’t supported though, which are a part of a cron spec. Might be a useful feature to add.

That's [Java's crontab-like syntax](https://docs.oracle.com/cd/E12058_01/doc/doc.1014/e12030/cron_expressions.htm), and I've never seen it implemented elsewhere. It is not part of any specification I'm aware of - certainly not [POSIX crontab](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html).

**Comment by Draxter** [comment]
Fair enough, I stand corrected. I guess I will need to stick with my ‘test’ workaround for unusual time intervals like “every second thesday”.

**Comment by smlx** [comment]
> Though even that is not ideal, as it counts as a failure on days other than Tuesday as far as gocrond is concerned, which triggers my alerting :(

You can fix this using an `if` statement:

```
if [ $(date +\%u) = 2 ]; then /files/job_1.sh; fi
```
