### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by n-rodriguez** [webdevops/go-crond#43]
Thank you!

**Comment by n-rodriguez** [comment]
ping @mblaschke thank you!

**Comment by n-rodriguez** [comment]
ping @mblaschke ! any news?

**Comment by mblaschke** [comment]
@n-rodriguez will create a new release tomorrow

**Comment by mblaschke** [comment]
have to move it another day due to some private issues, sorry

**Comment by n-rodriguez** [comment]
ping @mblaschke

**Comment by n-rodriguez** [comment]
Done: https://github.com/webdevops/go-crond/releases/tag/23.12.0
